default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails-action-cable-chat_dev

test:
  <<: *default
  database: rails-action-cable-chat_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
